<?php
error_reporting(0);
include 'connect.php';


if(isset($_POST['save']))
{
  $name= $_POST['name'];
  $email= $_POST['email'];
  $password =$_POST['password'];
  $ph= $_POST['ph'];
  $g = "SELECT * FROM users WHERE email='$email' ";
         $res= mysqli_query($conn,$g);
         $no_raw =mysqli_num_rows($res);
         if($no_raw){
     echo "<script>alert('Email already registered.Login with the email');</script>";
     echo "<script>location.replace('/Stadium/html/login.html')</script>";
  }
 else{
  $sql_query="INSERT INTO users (name,email,password,phnumber)
  VALUES ('$name','$email','$password' ,'$ph') ";
  $data = mysqli_query($conn,$sql_query);
 
  if($data){
    $to_email ='$email';
    $subject ='Thank you for Registering';
    $body = 'This is an Autogenerated email.';
    $headers ='From:stadiumforu@gmail.com';
    if(mail($to_email,$subject,$body,$headers)){
       echo "Sent";
    }
    else{
      echo "Not sent";
    }
  	echo "<script>alert('Thank you for Signing up.Login to your Account')</script>";
  	echo "<script>location.replace('/Stadium/html/login.html')</script>";
  }
} 
}
  ?>
 